fun/duck.cc.lua
=> Satty9361 duck

fun/SlotMachine.cc.lua
Just a simple slot machine game!
=> Added a Slot Machine Game to the Fun folder.

util/bigemoji_v2.cc.lua
bigemoji command that also works with builtin emojis
=> Bigemoji version 2

README.md
=> updated your tag :)

util/reactionlogs.cc.lua
Apart from being a nice reaction logging code i think its a a very useful snippet to learn a variety of advanced concepts -
- usage of print vs printf vs joinStr
- usage of with vs if
- usage of $ inside with
- using toRune
- specifying integer literals in hexadecimal format
- link to an user's profile card
- trimming whitespace
=> Simple reaction logger setup.

birthday/README.md, birthday/birthday.cc.lua
Added a -delbday command
Created a readme because of 10k limit
Fixed two bugs related to underage users
=> Birthday Command improvement

emojiSuggest/emojiSuggest.cc.lua
=> Fixed unexpected line ending

afk/afk.cc.lua
Didn't think I would be doing this since its only one character but yeah :))
=> Change trigger for afk.cc.lua

info/avatar.cc.lua, info/channel.cc.lua, info/server.cc.lua, info/user.cc.lua, leveling/leaderboard.cc.lua, leveling/leveling.cc.lua, leveling/rank.cc.lua, leveling/role-rewards.cc.lua, leveling/setxp.cc.lua, maintenance/addCommas.cc.lua, maintenance/ordinal.cc.lua, maintenance/send.cc.lua, maintenance/struct.lua, suggestion/v1/deleteSuggestion.cc.lua, suggestion/v1/editSuggestion.cc.lua, suggestion/v1/suggestAdmin.cc.lua, util/bigemoji-v2.cc.lua, util/bigemoji.cc.lua, util/preview.cc.lua, util/randomcolor.cc.lua
Some commands have old regex. So I decided to modified these.
All new regex are tested and it works perfectly.
=> Update regex in some commands

info/server.cc.lua
Make command work with animated server icon.
Code made by the author of this repository.
=> Fix server icon in server command

snippets/binarySearch.go.tmpl
I added new snippet called **Binary Search**.
**Status**
Finished, no error
=> New Snippet: Binary Search

snippets/binarySearch.go.tmpl
It missing an end so I add it.
**Status**
Finished
=> fix(binarySearch): add missing end inside define

moderation/reports/README.md, moderation/reports/cancelReport.go.tmpl, moderation/reports/customReport.go.tmpl, moderation/reports/reactionHandler.go.tmpl
This pull requests adds a report system, enhancing the native report command with additional functionalities.
These CCs allow users to create a report system with the ability for their server members to request cancellation/nullification of their reports and adding some functionalities for staff utilizing reactions. All necessary information is arranged in an embed which is edited accordingly.
The system should be documented well enough for users with basic CC knowledge on how to add and set up this package.
Please take the time to read the documentation found in the README.md, as this is the crucial part for user accessibility and suggest possible changes.
The code was tested thoroughly and should be stable, as long as the end user only changes the parts which are intended for changing. …
=> added report system

afk/afk.go.tmpl
=> fix(afk): too many required args

suggestion/README.md
This PR makes the instructions on how to setup the suggestion-cc a bit clearer.
**Status**
=> docs(suggestion): make instructions clearer

info/channel.go.tmpl
This fixes issue #151.
There is not much to explain 😉
**Status**
=> fix(info/channel): missing channel type

info/server.go.tmpl
Mistake in line 20 that was repeated from line 21
**Status**
=> Correct line 20

suggestion/suggestion.go.tmpl
=> fix(suggestion): escape $ and ^ properly for prefix

CONTRIBUTING.md
Folder `tools/` was renamed to `util/`, so update that in `CONTRIBUTING.md` file
**Status**
=> docs(contributing): Rename a folder mention

info/channel.go.tmpl
=> style(channel): use spaces after brackets

util/bookmark.gotmpl
The very first iteration of my bookmark CC.
As I decided to replace this code with a newer version pretty soon I thought it would be nice to share a basic version with the official repo.
~~Also I want to get that sweet sweet merge.~~
RegEx trigger with `\A(?:-\s?|<@!?204255221017214977>\s*)b(?:ook)?m(?:ark)?(?:\s+|\z)`
Mimicks the classic YAG command structure: 
* Mentioning yaggy also works
* Command alias `bookmark` and `bm`
Apart from the trigger, there is no configuration needed.
**Status**
---
I guess I'll also PR the first version of my report system soon, as I am working on a third version currently.
Don't need more than two versions at a time.
=> feat(util): bookmark

fun/Wheel of Fortune.go.tmpl
=> Create Wheel of Fortune.go.tmpl

moderation/report system/reactionHandler.go.tmpl
fixes #173
I am an idiot.
I am an idiot.
**Status**
=> fix(reports): hotfix invalid dict call

util/ghostping-v1.go.tmpl, util/ghostping-v2.go.tmpl, util/json.go.tmpl
Additions:
- json converter CC (jsonify)
- ghostping CC v1
- ghostping CC v2
**Status**
=> Small Util Update

afk/README.md, afk/afk.go.tmpl, suggestion/README.md, suggestion/suggestion.go.tmpl
This pull request adds the latest markdown files to `master`, as issue #186 tracks.
It includes a reworked documentation for the afk system as well as the suggestion system.
I think I made a pretty good job at guiding the user through the process of installing, catching possible questions and problems, and explaining the configuration variables, if applicable.
This is more meant as a midterm action, as there are surely still some files to work on, however I think we shouldn't withhold updates for too long.
**Status**
=> Midterm markdown refactor

fun/starboard v2/readme.md, fun/starboard v2/starboard.go.tmpl, fun/starboard v2/starboardListener.go.tmpl
make starboard great again
**Status**
=> add starboard v2

fun/starboard v2/readme.md
added another troubleshooting item as I believe I've seen this twice now
**Status**
=> add troubleshoot information to readme

fun/tte.go.tmpl
Simply, this is the updated regex since it's currently the old one that was used months ago for a lot of regex commands in here. Not many people use this cc, but since it's here it's probably best to update it.
**Status**
=> update tte/emojify Regex

moderation/staffOnDuty.go.tmpl
new CC for an "on duty" staffing system, read header for more information. Tested extensively on both premium and non premium servers. Heavily restricted topic editing to ensure discord ratelimit is not reached
**Status**
=> [feat] add staffOnDuty.go.tmpl

moderation/staffOnDuty.go.tmpl, util/bigEmoji-v2.go.tmpl
Simple change, just updating regex for both.
**Status**
=> chore(bigemojiv2,staffOnDuty): update regex

fun/connect4System/ReadMe.md, fun/connect4System/reactionListener.go.tmpl, fun/connect4System/startCmd.go.tmpl
Hello, this is my own version of the connect4 custom command.
At first I was thinking to just leave this on my repo, but, I didn't enjoy the thought of someone else's code of the same thing being PRed xD.
Anyways, hope this doesn't go against the guidelines. Thanks for checking out my pull request.
**Features:**
- a working gameTie/win/loss system
- a turn based embed that'll help the player recognize what their color is
- drops are highlighted in blue to help see the last player's move
**Status**
=> Another Connect4System

.github/workflows/continuous-integration.yml, fun/deathmatch.go.tmpl, fun/starboard.go.tmpl, snippets/cmdArgs.go.tmpl, snippets/ordinal.go.tmpl, snippets/snowflake2time.go.tmpl
Finally working about a lot of painful troubleshooting :D
Opening a PR to make sure the annotations work fine too.
=> ci(github): add check template syntax job

website/docs/moderation/report-system/reaction-handler.md
Adds a brief statement about the reaction handler in the report system being restricted to the report logging channel
**Status**
- [✔ ] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [✔ ] I have read and followed the [contribution guide](../CONTRIBUTING.md)
- [✔ ] I have [written documentation](../WRITING-DOCUMENTATION.md) for my changes, or there is no need to
=> add a brief thing about the channel restriction

.github/workflows/ci.yml
=> ci(github): bump syntax check action version again

README.md, website/docs/introduction.md
=> docs(*): copyedit readme, intro

src/fun/counting.go.tmpl
See discussion yagpdb-cc/yagpdb-cc#253.
**Status**
=> counting: wrap addReactions in try-catch

src/info/channel.go.tmpl, src/info/user.go.tmpl
Updates the src/info/channel.go.tmpl and src/info/user.go.tmpl files to use present-day functions.
For the user command, roles were restructured to be in order of server role list position.
Other small additions and changes listed specifically in each commit.
**Status**
=> Updating src/info channel.go.tmpl and user.go.tmpl

src/fun/counting_v2.go.tmpl
Continuation of https://github.com/yagpdb-cc/yagpdb-cc/pull/349
**Status**
=> CountingV2: fix takeRole function calls

src/fun/anon_channel/anon.go.tmpl
=> bug: db inconsistency
