fun/meme.cc.lua

The paren was causing sendMessage to error with too many args

moved a paren

---

LICENSE

Why MIT? Because most other repos by @Jo3-L already use MIT and it matches the [yagpdb license](https://github.com/jonas747/yagpdb/blob/master/LICENSE)

fix: added MIT LICENSE file

---

suggestion/v2/README.md

Some notes:
- In `Configuration Variables -> 4.` I've seen this, but I'm not sure if that's OK:
> This provides a good way to organise all approved suggestions. This provides a good way to organise all implemnted suggestions into a separate channel.
- In `Configuration Variables -> 7. and 8.` I've edited this:
> Supports both custom as well as inbuilt emojis, for which it is recommended...
Is that better than previous redaction?

Fix some typos on SuggestionV2's README

---

fun/CAHPackGroups/README.md
fun/CAHPackGroups/delgroup.go.tmpl
fun/CAHPackGroups/endgame.go.tmpl
fun/CAHPackGroups/listgroups.go.tmpl
fun/CAHPackGroups/newgame.go.tmpl
fun/CAHPackGroups/setgroup.go.tmpl

This PR adds a new set of custom commands, aimed at Cards Against Humanity (CAH) players. Specifically, these commands allow server members to create custom *groups of packs* from the built-in `cah` system.
While the README and descriptive blocks in each file provide additional details, the general outlines are as follows:
- Groups of packs are created and stored in YAGPDB's database system, and can be edited at any time. No validation is performed upon editing (so a user could add a nonexistent pack to a group).
- When the `newgame` command is used, all arguments that match existing pack groups are expanded into their constituent packs. Other arguments are assumed to be individual packs and are left alone. The resulting set of packs is then used to start a new CAH game, and members with …

Add CC set for custom groups of Cards Against Humanity packs

---

util/cc2file.go.tmpl

I add a new CC, which sends your CCs in text files, rather than Discord messages. This preserves tabs, markdown and doesn't flood the chat
**Status**
Functional, but can be improved:
- ~~File content is **full** `-cc` output, not only the extracted code from it~~ Done
- ~~Delete my comments? To reduce code size (chars)~~ Done, but I can put them back
- ~~You can't search using trigger. Only CC ID~~ Fixed
- ~~Export more than one CC in one execution. For example, `-cc2file 11 22 33` would return 3 files, one with each CC~~ Done!
Now it has a bug: Output to `-cc2file` (with no arguments, it generates CC list) if your server has a lot of CCs, was
> Custom command response was longer than 2k (contact an admin on the …

New CC: Send CC codes in text files

---

birthday/README.md
birthday/birthday.go.tmpl

Added $yearOptional as a true/false variable and slightly changed how $year is parsed. Default year is 2000 to allow February 29 as a valid date.
Works as far as I tested.
Inverted mode works, setbday works, and mybday works.
- [ x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [ x] I have read and followed the [contribution guide](../CONTRIBUTING.md)
Resolves #139

Allow year to be optional in the birthday command

---

suggestion/suggestion.go.tmpl

This fixes #141.
The Prefix check was performed incorrectly, causing it to error out. 
**Status**

fix(suggestion): server prefix error

---

suggestion/suggestion.go.tmpl

Very rookie mistake, oversaw a `reFindAllSubmatches` causing it to error out with certain prefixes.
**Status**

fix(suggestion): correct regex construction

---

moderation/reports/README.md

This PR garnishes the report system documentation with a more detailed explanation, featuring screenshots of both the moderation tab and the command override disabling the native report command.
This is by no means an urgent addition, however latest events made me do these changes quickly.

docs(moderation/reports): more detailed documentation

---

util/cc2file.go.tmpl

This update brings some features:
- Ability to limit execution to 5 CCs
- Ability to show/hide the info of each CC, in message's content and/or attachment's content (it's inserted as a comment)²
- Ability to blacklist CCs to maintain its code private¹
And some minor changes:
- `sendLongMessage` template now uses an `sdict` rather than a `cslice`
- Heavily-commented code: This is mostly for people who has to troubleshoot my code, if there are problems in a future
I didn't really test every single combination of options, but yeah, it works ;)
Some improvements that can be done:
1. Allow some users/roles to override blacklist?
2. Parse `$firstLine`'s content, extract CC info and print it in a format similar to this repo's Leading comments. Something like:
```go
//Before:
{{/* CC INFO: #20 - …
```

cc2file - Medium update

---

fun/funinfo.go.tmpl

This was that cc that accesses the data that is acquired when using the qotd and/or x-word-story (and my own counting) cc. If this one doesn't get added, then I'll make a PR that removes the feature in both of the latter CCs that gathers the data.

Added funinfo

---

util/bigemoji.go.tmpl

updated the bigemoji command to not use the google emoji pack, but use the twemoji pack which represents the discord emojis
**Status**

changed google emojis to twemojis

---

util/bigEmoji-v2.go.tmpl

Once again I have taken a simple command and made it overly complicated :ye: 
Stripped down and rebuilt the existing big emoji CC to increase feature set:
- base functionality retained (one emote -> image embed)
- now provides emote name and image/gif direct link along with the image embed
- allow usage of message ID and link to scrape emotes from other messages
- also supports pulling emotes from reactions with optional flag 
- support for up to 25 emotes per message (in either trigger or external message)
- generates a list of emotes names with direct image links to each
- changed default emoji image provider to the official Twemoji repo
- Twemoji is open source and free to use. I've included attribution per …

Add new bigEmoji-v2.go.tmpl CC

---

src/leveling/leveling.go.tmpl
src/moderation/lockdown.go.tmpl
src/moderation/staff_on_duty.go.tmpl
src/utilities/edit.go.tmpl
src/utilities/json.go.tmpl
src/utilities/send.go.tmpl
website/src/custom-languages/prism-gotmpl/funcs.js

The current implementation of `getChannel` may throw an error, which is
generally undesirable. This commit audits the usage of said function
and, depending on case, opts to use `.Guild.GetChannel` or
`getChannelOrThread`.
In cases where an actual, solid channel is needed, `.Guild.GetChannel`
is to be used, otherwise `getChannelOrThread`.
Closes yagpdb-cc/yagpdb-cc#237
**Status**

leveling/moderation/utils/website: review getChannel usage

---

website/docs/birthday/overview.md

Hi! I was adding that CC to my server, until I've read [docs for `$yearOptional`](https://yagpdb-cc.github.io/birthday/overview#list-of-configurable-values). English is not my native language, so I didn't originally understand this:
> [...] should a member not give a year upon configuring their birthday.
This PR gives an easier to understand phrase, at least for me
**Status**

docs(birthday#overview): Edit a phrase

---

website/docs/birthday/overview.md

Hi! [Here](https://yagpdb-cc.github.io/birthday/overview#commands) the documented syntax is `setbirthday <user>`, but when running the command, `parseArgs` says
> Correct syntax is: `-setbday date @user`
**Status**

docs(birthday#commands): Fix missing argument for `setbirthday`

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #265. Currently, GitHub does weird stuff with relative links on PRs, so this may break again in the future
If you go to "real" `PULL_REQUEST_TEMPLATE.md` file, URLs won't work. But they do if you open a PR
Just in case: [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md) [`WRITING-DOCUMENTATION.md`](../blob/master/WRITING-DOCUMENTATION.md)
PS: Sorry for shitty commit names
**Status**

repo(pr_template): Fix broken URLs

---

src/afk/afk.go.tmpl
src/fun/coinflip.go.tmpl
src/fun/counting.go.tmpl
src/moderation/nickname_moderation.go.tmpl
src/moderation/report_system/cancel_report.go.tmpl
src/moderation/report_system/custom_report.go.tmpl
src/suggestion/suggestion.go.tmpl

`.ServerPrefix` removes the need for having to index with `exec "prefix"` that many of these CCs use. Also just saves few more chars.
Small Note: I did not feel the birthday CC required this change as it does not specifically check if it's the server's prefix, only getting the prefix used to run the CC.
**Status**

Update CCs to use .ServerPrefix

---

src/moderation/nickname_moderation.go.tmpl
src/moderation/report_system/custom_report.go.tmpl
src/moderation/report_system/reaction_handler.go.tmpl
src/moderation/slowmode.go.tmpl
src/suggestion/suggestion.go.tmpl

This pull request replaces all usages of `viewperms` with `exec` to check permissions of current user, with brand new `.Permissions` and `hasPermissions`, which [may be considered as safer and more efficient option](https://github.com/botlabs-gg/yagpdb/pull/894), and in most cases, reduces complexity as well.
**Status**

Replace usages of viewperms

---

.github/workflows/ci.yml

This commit bumps the jo3-l/action-check-yag-tmpl-syntax action to its
latest release, v2.0.2.
With this change, new pipelines should no longer fail when they use new
template functions.
----
**Status**

github: bump template check action

---

src/leveling/leaderboard.go.tmpl

This commit improves the leaderboard of the levelling system to show the
ID instead of a blank #, should they have left the server.
Closes #230
**Status**

leveling: improve leaderboard display

---

website/docusaurus.config.js

This commit adds algolia's docsearch to the website frontend.
Visitors can now launch the search modal via <C-k>, which is populated
with records from algolia's crawler.
Closes #229
**Status**

website: add algolia docsearch

---

src/moderation/slowmode.go.tmpl

Fixes invalid syntax introduced in 6848f5682f026bc440e5e75fc34a5db49c364913
Adds indentation to improve readability
**Status**

fix(slowmode): add missing parens

---

website/docs/moderation/lockdown.md

`\A` as regex trigger only tests for the start-of-line character, thus 
not populating `.Cmd`, which the custom command checks for.
This commit removes that trigger from the list.
**Status**

docs/moderation: remove `\A` trigger from lockdown

---

website/docs/moderation/nickname-moderation.mdx

Remove `.*` as regex trigger from the nickname moderation documentation, because the command checks for `.CmdArgs`, which won't be populated with a `.*` trigger.
Instead, one must use `\A`, which'll work as expected.
**Status**

docs/moderation: remove `.*` from nickname mod

---

website/docs/afk/main-cc.md

Add `.*` as a possible regex trigger to the list of triggers.
It works just as well.
**Status**

docs/afk: add `.*` as possible trigger

---

README.md
website/docs/introduction.md

Remove the "official" remark and replace it with the similar, but less
assertive term "vetted".
Add to the "Need help" section that not every staff may know about every
custom command present here.
The rationale behind this change is the fact that "official" implies
that all staff are more or less knowledgeable about the codebase present
in this collection, which is simply not true.
Further, it cannot be reasonably expected that all staff *are* indeed
knowledgeable about this collection.
"Vetted" has a similar meaning, though it is less assertive:
Someone with good knowledge has looked at the code and confirmed it to
be -- to the best of their abilities -- free of malicious code.
Third-party content always has a risk with it, which is also noted down
(though to a different extent) in …

docs: remove official remark

---

src/utilities/snipe.go.tmpl

Refactor the snipe utility CC to support Pomelo user strings and use
more clear logic.
Behaviour is the same except warning messages are prepended to the
embed footer text instead of the embed description, and image URLs after
other URLs will no longer be detected, for simplicity.
**Status**

refactor(snipe): use up-to-date styles, fix user string regex

---

src/fun/starboard_v2/starboard.go.tmpl

Fix attachments not embedding properly due to no match being found.
Discord recently changed how attachment URLs are constructed[^1]. They
now have URL parameters, which the current implementation does not
account for.
Removing the constraint to match the file extension and then an EOL
reportedly fixes this issue[^2].
I decided against a more complex regex to match against the URL
parameters as well. If this causes undesirable behaviour in the future,
it is obviously subject to change.
[^1]: https://www.bleepingcomputer.com/news/security/discord-will-switch-to-temporary-file-links-to-block-malware-delivery/
[^2]: https://discord.com/channels/166207328570441728/384011387132706816/1170826121462415400
Reported-by: majorleaguebutters (Discord)
Reported-by: @FravBox
Tested-by: …

starboardv2: fix attachments not embedding

---

src/fun/counting_v2.go.tmpl
website/docs/fun/counting_v2.md

This version of a counting command allows for the usage of base 10 and roman numerals, optionally joined by the usage of math functions and/or operators to count from 1, incrementing by 1, until failure.
With a range of configurable variables, the user can chose to have the ability to count twice, or more, in a row, roles for correct counting users and incorrect counting users, effectively allowing a blacklist; saves, reactions, and more!
Also bundled in this command is a statistics command, with optional arguments to view server or user stats individually or a leaderboard for users which have counted correctly the most times.
Possible changes/request for help deciding
- As the character count is nearly 10k, even …

counting: add counting v2 command

---

src/fun/counting_v2.go.tmpl

This PR changes from using `addRoleID` and `removeRoleID` to `addRole` and `removeRole` respectively. This comes after a change was made to only allow role IDs - and not role objects as provided as the argument to these functions - to be parsed by the previous functions.
There is one other slight change for a condition which removed a `joinStr` call that was not needed.
**Status**

CountingV2: fix role function calls

---

src/fun/coinflip.go.tmpl
website/docs/fun/coinflip.md

Initiate a draft PR for coinflip.
I intended to remove the nesting of if statements. I have realized after a deeper review, that many things can and should be updated, so much so that I would rather rewrite the command in my own fashion. I believe coinflip is a simple command and does not necessarily need a second version; but how could we preserve David's involvement if I were to rewrite it? I will include most features in my rewrite, but notably removing the need for a channel list and `scheduleUniqueCC`.
**Status**

fun/coinflip: rewrite

---

src/fun/qotd/advanced/component_handler.go.tmpl

Addresses a race condition where the component handler and a CC it executes would fight for the last DB assignment for config. Now the component handler is a nice guy, and additionally it  merges the config from both CCs before saving.
Signed-off-by: SoggySaussages <vmdmaharaj@gmail.com>
**Status**

bug: race condition
